[versions]
agp = "8.11.1"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
kotlinxSerialization = "1.8.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.16.0" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.10.1" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.10.1" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2025.06.01" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-core", version = "1.7.8" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.9.0" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.9.1" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version = "2.7.1" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version = "2.7.1" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version = "2.7.1" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version = "2.10.1" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version = "21.3.0" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version = "24.0.1" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version = "26.0.0" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version = "25.0.1" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
